// This script is designed to test the solidity smart contract - SuppyChain.sol -- and the various functions within
// Declare a variable and assign the compiled smart contract artifact
var SupplyChain = artifacts.require('SupplyChain')

contract('SupplyChain', function(accounts) {
    // Declare few constants and assign a few sample accounts generated by ganache-cli
    var sku = 1
    var sn = 1
    const ownerID = accounts[0]
    const originShopID = accounts[1]
    const originShopName = "Av MRO Shop"
    const originShopInformation = "Cincy"
    const originShopLatitude = "39.103119"
    const originShopLongitude = "-84.512016"
    var productID = sku + sn
    const productNotes = "Fan Disk - LLP"
    const productPrice = web3.toWei(1, "ether")
    var itemState = 0
    const distributorID = accounts[2]
    const storeID = accounts[3]
    const buyerID = accounts[4]
    const emptyAddress = '0x00000000000000000000000000000000000000'

    ///Available Accounts
    ///==================
    ///(0) 0x27d8d15cbc94527cadf5ec14b69519ae23288b95
    ///(1) 0x018c2dabef4904ecbd7118350a0c54dbeae3549a
    ///(2) 0xce5144391b4ab80668965f2cc4f2cc102380ef0a
    ///(3) 0x460c31107dd048e34971e57da2f99f659add4f02
    ///(4) 0xd37b7b8c62be2fdde8daa9816483aebdbd356088
    ///(5) 0x27f184bdc0e7a931b507ddd689d76dba10514bcb
    ///(6) 0xfe0df793060c49edca5ac9c104dd8e3375349978
    ///(7) 0xbd58a85c96cc6727859d853086fe8560bc137632
    ///(8) 0xe07b5ee5f738b2f87f88b99aac9c64ff1e0c7917
    ///(9) 0xbd3ff2e3aded055244d66544c9c059fa0851da44

    console.log("ganache-cli accounts used here...")
    console.log("Contract Owner: accounts[0] ", accounts[0])
    console.log("Shop: accounts[1] ", accounts[1])
    console.log("Other: accounts[2] ", accounts[2])
    console.log("Store: accounts[3] ", accounts[3])
    console.log("Buyer: accounts[4] ", accounts[4])


    it("Can instantiate the contract", async () => {
        
        const supplyChain = await SupplyChain.deployed()
        let result = await supplyChain;
        assert.exists(result, "contract is instantiated");

      })


    it("Can remove Item, fetchItemBufferOne", async () => {
        const supplyChain = await SupplyChain.deployed()
        
        await supplyChain.removeItem(
            sku,
            originShopID,
            originShopName,
            originShopInformation,
            originShopLatitude,
            originShopLongitude,
            productNotes,
            { from: accounts[1], gas: 1000000 }
        );
        let item = await supplyChain.fetchItemBufferOne.call(1)
        
        //console.log("Removed Item", item)

        // item vector index relates to fetchItemBufferOne
        assert.equal(item[0].toString(), sku, "sku match error");
        assert.equal(item[4].toString(), originShopName, "originShopName match error");
        assert.equal(item[5].toString(), originShopInformation, "originShopInformation match error");
        assert.equal(item[6].toString(), originShopLatitude, "originShopLatitude match error");
        assert.equal(item[7].toString(), originShopLongitude, "originShopLongitude match error");
        assert.equal(item[8].toString(), productNotes, "productNotes match error");
    });




    // 2nd Test
    it("Testing smart contract function cleanInspectItem() that allows a shop to clean/inspect part", async() => {
        const supplyChain = await SupplyChain.deployed()
        
        // Declare and Initialize a variable for event
        var cleanInspectEvent = false;
        
        // Mark an item as cleanInspect by calling function processtItem()
        await supplyChain.cleanInspectItem(sn,{from: originShopID, gas: 1000000});
        
        // Watch the emitted event Built()
        // var event = supplyChain.cleanInspectItem()
        // await event.watch((err, res) => {
        //     cleanInspectEvent = true
        // })
        

        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        let itemBufferOne = await supplyChain.fetchItemBufferOne.call(sn)
        
        console.log("itemBufferOne: ", itemBufferOne);

        let itemBufferTwo = await supplyChain.fetchItemBufferTwo.call(sn)

        //console.log("itemBufferTwo: ", itemBufferTwo);
        console.log("itemBufferTwo State Enum:", itemBufferTwo[5].toNumber())

        // Verify the result set
        assert.equal(itemBufferOne[0], sku, "sku match error");
        assert.equal(itemBufferOne[4].toString(), originShopName, "originShopName match error");
        assert.equal(itemBufferOne[5].toString(), originShopInformation, "originShopInformation match error");
        assert.equal(itemBufferOne[6].toString(), originShopLatitude, "originShopLatitude match error");
        assert.equal(itemBufferOne[7].toString(), originShopLongitude, "originShopLongitude match error");
        assert.equal(itemBufferOne[8].toString(), productNotes, "productNotes match error");
        assert.equal(itemBufferTwo[5], 1, 'state check failed')
        
    })    

    // 3rd Test
    it("Testing smart contract function shipItem() that allows a shop to ship the item", async() => {
        const supplyChain = await SupplyChain.deployed()
        
        // Declare and Initialize a variable for event
        var cleanInspectEvent = false;
        
        // Watch the emitted event Packed()
        

        // Mark an item as Packed by calling function packItem()
        

        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        

        // Verify the result set
        
    })    

//     // 4th Test
//     it("Testing smart contract function sellItem() that allows a farmer to sell coffee", async() => {
//         const supplyChain = await SupplyChain.deployed()
        
//         // Declare and Initialize a variable for event
        
        
//         // Watch the emitted event ForSale()
        

//         // Mark an item as ForSale by calling function sellItem()
        

//         // Retrieve the just now saved item from blockchain by calling function fetchItem()
        

//         // Verify the result set
          
//     })    

//     // 5th Test
//     it("Testing smart contract function buyItem() that allows a distributor to buy coffee", async() => {
//         const supplyChain = await SupplyChain.deployed()
        
//         // Declare and Initialize a variable for event
        
        
//         // Watch the emitted event Sold()
//         var event = supplyChain.Sold()
        

//         // Mark an item as Sold by calling function buyItem()
        

//         // Retrieve the just now saved item from blockchain by calling function fetchItem()
        

//         // Verify the result set
        
//     })    

//     // 6th Test
//     it("Testing smart contract function shipItem() that allows a distributor to ship coffee", async() => {
//         const supplyChain = await SupplyChain.deployed()
        
//         // Declare and Initialize a variable for event
        
        
//         // Watch the emitted event Shipped()
        

//         // Mark an item as Sold by calling function buyItem()
        

//         // Retrieve the just now saved item from blockchain by calling function fetchItem()
        

//         // Verify the result set
              
//     })    

//     // 7th Test
//     it("Testing smart contract function receiveItem() that allows a retailer to mark coffee received", async() => {
//         const supplyChain = await SupplyChain.deployed()
        
//         // Declare and Initialize a variable for event
        
        
//         // Watch the emitted event Received()
        

//         // Mark an item as Sold by calling function buyItem()
        

//         // Retrieve the just now saved item from blockchain by calling function fetchItem()
        

//         // Verify the result set
             
//     })    

//     // 8th Test
//     it("Testing smart contract function purchaseItem() that allows a consumer to purchase coffee", async() => {
//         const supplyChain = await SupplyChain.deployed()
        
//         // Declare and Initialize a variable for event
        
        
//         // Watch the emitted event Purchased()
        

//         // Mark an item as Sold by calling function buyItem()
        

//         // Retrieve the just now saved item from blockchain by calling function fetchItem()
        

//         // Verify the result set
        
//     })    

//     // 9th Test
//     it("Testing smart contract function fetchItemBufferOne() that allows anyone to fetch item details from blockchain", async() => {
//         const supplyChain = await SupplyChain.deployed()

//         // Retrieve the just now saved item from blockchain by calling function fetchItem()
        
        
//         // Verify the result set:
        
//     })

//     // 10th Test
//     it("Testing smart contract function fetchItemBufferTwo() that allows anyone to fetch item details from blockchain", async() => {
//         const supplyChain = await SupplyChain.deployed()

//         // Retrieve the just now saved item from blockchain by calling function fetchItem()
        
        
//         // Verify the result set:
        
//     })

});